title: Necro Notes
description: Entrepreneur, CTO, Unemployed - choose two
url: "https://necromant2005.github.io"
baseurl: ""
timezone: UTC
markdown: kramdown
permalink: /:title/

author:
  name: Necro
  bio: Notes on code, ideas, and projects.

collections:
  pages:
    output: true

defaults:
  - scope:
      path: ""
    values:
      layout: default
  - scope:
      path: ""
      type: posts
    values:
      layout: post
  - scope:
      path: "_pages/dev"
    values:
      category: Dev
      permalink: /dev/:basename/
  - scope:
      path: "_pages/management"
    values:
      category: Management
      permalink: /management/:basename/
  - scope:
      path: "_pages/analytics"
    values:
      category: Analytics
      permalink: /analytics/:basename/
  - scope:
      path: "_pages/other"
    values:
      category: Other
      permalink: /other/:basename/

exclude:
  - README.md
